/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.gui;

/**
 *
 * @author Tincho
 */
public class InicioSesion extends javax.swing.JPanel {

    private Main mainFrame;

    public InicioSesion(Main mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelLogin = new javax.swing.JLabel();
        LabelUsuarioInicioSesion = new javax.swing.JLabel();
        TextFieldUsuarioInicioSesion = new javax.swing.JTextField();
        LabelContraseñaInicioSesion = new javax.swing.JLabel();
        PasswordFieldInicioSesion = new javax.swing.JPasswordField();
        ButtonOlvidéMiContraseñaInicioSesion = new javax.swing.JButton();
        ButtonRegistrarNuevoUsuarioInicioSesion = new javax.swing.JButton();
        ButtonIniciarSesiónInicioSesion = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));

        LabelLogin.setFont(new java.awt.Font("Aptos", 0, 24)); // NOI18N
        LabelLogin.setForeground(new java.awt.Color(255, 255, 255));
        LabelLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelLogin.setText("Log In");

        LabelUsuarioInicioSesion.setFont(new java.awt.Font("Aptos", 0, 18)); // NOI18N
        LabelUsuarioInicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        LabelUsuarioInicioSesion.setText("Usuario");

        TextFieldUsuarioInicioSesion.setBackground(new java.awt.Color(102, 102, 102));
        TextFieldUsuarioInicioSesion.setFont(new java.awt.Font("Aptos", 0, 12)); // NOI18N
        TextFieldUsuarioInicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        TextFieldUsuarioInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldUsuarioInicioSesionActionPerformed(evt);
            }
        });

        LabelContraseñaInicioSesion.setFont(new java.awt.Font("Aptos", 0, 18)); // NOI18N
        LabelContraseñaInicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        LabelContraseñaInicioSesion.setText("Contraseña");

        PasswordFieldInicioSesion.setBackground(new java.awt.Color(102, 102, 102));
        PasswordFieldInicioSesion.setFont(new java.awt.Font("Aptos", 0, 12)); // NOI18N
        PasswordFieldInicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        PasswordFieldInicioSesion.setText("jPasswordField1");
        PasswordFieldInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldInicioSesionActionPerformed(evt);
            }
        });

        ButtonOlvidéMiContraseñaInicioSesion.setBackground(new java.awt.Color(102, 102, 102));
        ButtonOlvidéMiContraseñaInicioSesion.setFont(new java.awt.Font("Aptos", 0, 14)); // NOI18N
        ButtonOlvidéMiContraseñaInicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        ButtonOlvidéMiContraseñaInicioSesion.setText("Olvidé mi contraseña");
        ButtonOlvidéMiContraseñaInicioSesion.setBorderPainted(false);

        ButtonRegistrarNuevoUsuarioInicioSesion.setBackground(new java.awt.Color(102, 102, 102));
        ButtonRegistrarNuevoUsuarioInicioSesion.setFont(new java.awt.Font("Aptos", 0, 14)); // NOI18N
        ButtonRegistrarNuevoUsuarioInicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        ButtonRegistrarNuevoUsuarioInicioSesion.setText("Registrar nuevo usuario");
        ButtonRegistrarNuevoUsuarioInicioSesion.setBorderPainted(false);

        ButtonIniciarSesiónInicioSesion.setBackground(new java.awt.Color(0, 102, 153));
        ButtonIniciarSesiónInicioSesion.setFont(new java.awt.Font("Aptos", 0, 14)); // NOI18N
        ButtonIniciarSesiónInicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        ButtonIniciarSesiónInicioSesion.setText("Iniciar Sesión");
        ButtonIniciarSesiónInicioSesion.setBorderPainted(false);
        ButtonIniciarSesiónInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIniciarSesiónInicioSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ButtonOlvidéMiContraseñaInicioSesion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(ButtonRegistrarNuevoUsuarioInicioSesion))
                    .addComponent(LabelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextFieldUsuarioInicioSesion)
                    .addComponent(PasswordFieldInicioSesion)
                    .addComponent(LabelUsuarioInicioSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelContraseñaInicioSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonIniciarSesiónInicioSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(239, Short.MAX_VALUE)
                .addComponent(LabelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelUsuarioInicioSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldUsuarioInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelContraseñaInicioSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordFieldInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonOlvidéMiContraseñaInicioSesion)
                    .addComponent(ButtonRegistrarNuevoUsuarioInicioSesion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonIniciarSesiónInicioSesion)
                .addContainerGap(239, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordFieldInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldInicioSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldInicioSesionActionPerformed

    private void TextFieldUsuarioInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldUsuarioInicioSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldUsuarioInicioSesionActionPerformed

    private void ButtonIniciarSesiónInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIniciarSesiónInicioSesionActionPerformed
        // TODO add your handling code here:
        //mainFrame.setVistaAdministrador();
        //mainFrame.setVistaVeterinario();
        mainFrame.setVistaVoluntario();
    }//GEN-LAST:event_ButtonIniciarSesiónInicioSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonIniciarSesiónInicioSesion;
    private javax.swing.JButton ButtonOlvidéMiContraseñaInicioSesion;
    private javax.swing.JButton ButtonRegistrarNuevoUsuarioInicioSesion;
    private javax.swing.JLabel LabelContraseñaInicioSesion;
    private javax.swing.JLabel LabelLogin;
    private javax.swing.JLabel LabelUsuarioInicioSesion;
    private javax.swing.JPasswordField PasswordFieldInicioSesion;
    private javax.swing.JTextField TextFieldUsuarioInicioSesion;
    // End of variables declaration//GEN-END:variables
}
