package com.gui;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

public class Main extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());

    private InicioSesion inicioSesion;
    private VistaAdministrador vistaAdministrador;
    private VistaVeterinario vistaVeterinario;
    private VistaVoluntario vistaVoluntario;
        private RegistrarUsuarioNuevo registrarUsuarioNuevo;

    public void setRegistrarUsuarioNuevo() {
        if (registrarUsuarioNuevo == null) {
            registrarUsuarioNuevo = new RegistrarUsuarioNuevo(this);
        }
        ContenedorMain.removeAll();
        ContenedorMain.add(registrarUsuarioNuevo);
        SwingUtilities.updateComponentTreeUI(ContenedorMain);
    }
    
    public void setInicioSesion() {
        if (inicioSesion == null) {
            inicioSesion = new InicioSesion(this);
        }
        ContenedorMain.removeAll();
        ContenedorMain.add(inicioSesion);
        SwingUtilities.updateComponentTreeUI(ContenedorMain);
    }

    
    public void setVistaAdministrador() {
        if (vistaAdministrador == null) {
            vistaAdministrador = new VistaAdministrador(this);
        }
        ContenedorMain.removeAll();
        ContenedorMain.add(vistaAdministrador);
        SwingUtilities.updateComponentTreeUI(ContenedorMain);
    }
    
    public void setVistaVeterinario() {
        if (vistaVeterinario == null) {
            vistaVeterinario = new VistaVeterinario(this);
        }
        ContenedorMain.removeAll();
        ContenedorMain.add(vistaVeterinario);
        SwingUtilities.updateComponentTreeUI(ContenedorMain);
    }
        
    public void setVistaVoluntario() {
        if (vistaVoluntario == null) {
            vistaVoluntario = new VistaVoluntario(this);
        }
        ContenedorMain.removeAll();
        ContenedorMain.add(vistaVoluntario);
        SwingUtilities.updateComponentTreeUI(ContenedorMain);
    }
    
    public Main() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setInicioSesion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContenedorMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ContenedorMain.setBackground(new java.awt.Color(51, 51, 51));
        ContenedorMain.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContenedorMain, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(ContenedorMain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContenedorMain;
    // End of variables declaration//GEN-END:variables
}
