/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.gui;

/**
 *
 * @author Tincho
 */
public class RegistrarUsuarioNuevo extends javax.swing.JPanel {

    private Main mainFrame;

    public RegistrarUsuarioNuevo(Main mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        LabelRegistro = new javax.swing.JLabel();
        LabelNombreRegistro = new javax.swing.JLabel();
        TextFieldNombreRegistro = new javax.swing.JTextField();
        LabelContraseñaRegistro = new javax.swing.JLabel();
        PasswordFieldRegistro = new javax.swing.JPasswordField();
        LabelConfirmarContraseñaRegistro = new javax.swing.JLabel();
        PasswordFieldConfirmarContraseña = new javax.swing.JPasswordField();
        LabelRolRegistro = new javax.swing.JLabel();
        ComboBoxRolRegistro = new javax.swing.JComboBox<>();
        ButtonRegistrar = new javax.swing.JButton();
        ButtonVolverInicioSesion = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));

        LabelRegistro.setFont(new java.awt.Font("Aptos", 0, 24)); // NOI18N
        LabelRegistro.setForeground(new java.awt.Color(255, 255, 255));
        LabelRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelRegistro.setText("Registrar Nuevo Usuario");

        LabelNombreRegistro.setFont(new java.awt.Font("Aptos", 0, 18)); // NOI18N
        LabelNombreRegistro.setForeground(new java.awt.Color(255, 255, 255));
        LabelNombreRegistro.setText("Nombre de Usuario");

        TextFieldNombreRegistro.setBackground(new java.awt.Color(102, 102, 102));
        TextFieldNombreRegistro.setFont(new java.awt.Font("Aptos", 0, 12)); // NOI18N
        TextFieldNombreRegistro.setForeground(new java.awt.Color(255, 255, 255));

        LabelContraseñaRegistro.setFont(new java.awt.Font("Aptos", 0, 18)); // NOI18N
        LabelContraseñaRegistro.setForeground(new java.awt.Color(255, 255, 255));
        LabelContraseñaRegistro.setText("Contraseña");

        PasswordFieldRegistro.setBackground(new java.awt.Color(102, 102, 102));
        PasswordFieldRegistro.setFont(new java.awt.Font("Aptos", 0, 12)); // NOI18N
        PasswordFieldRegistro.setForeground(new java.awt.Color(255, 255, 255));

        LabelConfirmarContraseñaRegistro.setFont(new java.awt.Font("Aptos", 0, 18)); // NOI18N
        LabelConfirmarContraseñaRegistro.setForeground(new java.awt.Color(255, 255, 255));
        LabelConfirmarContraseñaRegistro.setText("Confirmar Contraseña");

        PasswordFieldConfirmarContraseña.setBackground(new java.awt.Color(102, 102, 102));
        PasswordFieldConfirmarContraseña.setFont(new java.awt.Font("Aptos", 0, 12)); // NOI18N
        PasswordFieldConfirmarContraseña.setForeground(new java.awt.Color(255, 255, 255));

        LabelRolRegistro.setFont(new java.awt.Font("Aptos", 0, 18)); // NOI18N
        LabelRolRegistro.setForeground(new java.awt.Color(255, 255, 255));
        LabelRolRegistro.setText("Rol");

        ComboBoxRolRegistro.setBackground(new java.awt.Color(102, 102, 102));
        ComboBoxRolRegistro.setFont(new java.awt.Font("Aptos", 0, 12)); // NOI18N
        ComboBoxRolRegistro.setForeground(new java.awt.Color(255, 255, 255));
        ComboBoxRolRegistro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar rol...", "Administrador", "Veterinario", "Voluntario" }));

        ButtonRegistrar.setBackground(new java.awt.Color(0, 102, 153));
        ButtonRegistrar.setFont(new java.awt.Font("Aptos", 0, 14)); // NOI18N
        ButtonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonRegistrar.setText("Registrar");
        ButtonRegistrar.setBorderPainted(false);
        ButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegistrarActionPerformed(evt);
            }
        });

        ButtonVolverInicioSesion.setBackground(new java.awt.Color(102, 102, 102));
        ButtonVolverInicioSesion.setFont(new java.awt.Font("Aptos", 0, 14)); // NOI18N
        ButtonVolverInicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        ButtonVolverInicioSesion.setText("Volver a Inicio de Sesión");
        ButtonVolverInicioSesion.setBorderPainted(false);
        ButtonVolverInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVolverInicioSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(LabelNombreRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextFieldNombreRegistro)
                    .addComponent(LabelContraseñaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PasswordFieldRegistro)
                    .addComponent(LabelConfirmarContraseñaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PasswordFieldConfirmarContraseña)
                    .addComponent(LabelRolRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBoxRolRegistro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonVolverInicioSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(LabelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelNombreRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldNombreRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(LabelContraseñaRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordFieldRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(LabelConfirmarContraseñaRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordFieldConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(LabelRolRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxRolRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(ButtonVolverInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void ButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO: Aquí irá la lógica de validación y registro
        String nombre = TextFieldNombreRegistro.getText();
        String contrasena = new String(PasswordFieldRegistro.getPassword());
        String confirmarContrasena = new String(PasswordFieldConfirmarContraseña.getPassword());
        String rol = (String) ComboBoxRolRegistro.getSelectedItem();
        
        // Validaciones básicas
        if (nombre.trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Por favor ingrese un nombre de usuario", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (contrasena.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Por favor ingrese una contraseña", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!contrasena.equals(confirmarContrasena)) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Las contraseñas no coinciden", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (rol.equals("Seleccionar rol...")) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Por favor seleccione un rol", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // TODO: Aquí se implementará la lógica para guardar el usuario en la base de datos
        // Por ahora solo mostramos un mensaje de éxito
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Usuario registrado exitosamente", 
            "Éxito", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        // Volver al inicio de sesión
        mainFrame.setInicioSesion();
    }                                                

    private void ButtonVolverInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        mainFrame.setInicioSesion();
    }                                                        


    // Variables declaration - do not modify                     
    private javax.swing.JButton ButtonRegistrar;
    private javax.swing.JButton ButtonVolverInicioSesion;
    private javax.swing.JComboBox<String> ComboBoxRolRegistro;
    private javax.swing.JLabel LabelConfirmarContraseñaRegistro;
    private javax.swing.JLabel LabelContraseñaRegistro;
    private javax.swing.JLabel LabelNombreRegistro;
    private javax.swing.JLabel LabelRegistro;
    private javax.swing.JLabel LabelRolRegistro;
    private javax.swing.JPasswordField PasswordFieldConfirmarContraseña;
    private javax.swing.JPasswordField PasswordFieldRegistro;
    private javax.swing.JTextField TextFieldNombreRegistro;
    // End of variables declaration                   
}
