/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.gui;

/**
 *
 * @author Tincho
 */
public class VistaAdministrador extends javax.swing.JPanel {

    private Main mainFrame;

    public VistaAdministrador(Main mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OpcionesAdministrador = new javax.swing.JPanel();
        LabelUsuarioAdministrador = new javax.swing.JLabel();
        BotonGenerarReporte = new javax.swing.JButton();
        BotonDarDeBajaUsuarios = new javax.swing.JButton();
        BotonVerReputaciónDeVoluntarios = new javax.swing.JButton();
        BotonCerrarSesiónAdministrador = new javax.swing.JButton();
        ContenedorPrincipalAdministrador = new javax.swing.JPanel();

        setBackground(new java.awt.Color(51, 51, 51));

        OpcionesAdministrador.setBackground(new java.awt.Color(51, 51, 51));

        LabelUsuarioAdministrador.setFont(new java.awt.Font("Aptos", 0, 24)); // NOI18N
        LabelUsuarioAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        LabelUsuarioAdministrador.setText("Usuario:");
        LabelUsuarioAdministrador.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        BotonGenerarReporte.setBackground(new java.awt.Color(0, 102, 153));
        BotonGenerarReporte.setFont(new java.awt.Font("Aptos", 0, 18)); // NOI18N
        BotonGenerarReporte.setForeground(new java.awt.Color(255, 255, 255));
        BotonGenerarReporte.setText("Generar reporte");
        BotonGenerarReporte.setBorderPainted(false);
        BotonGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGenerarReporteActionPerformed(evt);
            }
        });

        BotonDarDeBajaUsuarios.setBackground(new java.awt.Color(0, 102, 153));
        BotonDarDeBajaUsuarios.setFont(new java.awt.Font("Aptos", 0, 18)); // NOI18N
        BotonDarDeBajaUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        BotonDarDeBajaUsuarios.setText("Dar de baja usuarios");
        BotonDarDeBajaUsuarios.setBorderPainted(false);
        BotonDarDeBajaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDarDeBajaUsuariosActionPerformed(evt);
            }
        });

        BotonVerReputaciónDeVoluntarios.setBackground(new java.awt.Color(0, 102, 153));
        BotonVerReputaciónDeVoluntarios.setFont(new java.awt.Font("Aptos", 0, 18)); // NOI18N
        BotonVerReputaciónDeVoluntarios.setForeground(new java.awt.Color(255, 255, 255));
        BotonVerReputaciónDeVoluntarios.setText("<HTML>Ver reputación de voluntarios</HTML>");
        BotonVerReputaciónDeVoluntarios.setBorderPainted(false);
        BotonVerReputaciónDeVoluntarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVerReputaciónDeVoluntariosActionPerformed(evt);
            }
        });

        BotonCerrarSesiónAdministrador.setBackground(new java.awt.Color(0, 102, 153));
        BotonCerrarSesiónAdministrador.setFont(new java.awt.Font("Aptos", 0, 14)); // NOI18N
        BotonCerrarSesiónAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        BotonCerrarSesiónAdministrador.setText("Cerrar Sesión");
        BotonCerrarSesiónAdministrador.setBorderPainted(false);
        BotonCerrarSesiónAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrarSesiónAdministradorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OpcionesAdministradorLayout = new javax.swing.GroupLayout(OpcionesAdministrador);
        OpcionesAdministrador.setLayout(OpcionesAdministradorLayout);
        OpcionesAdministradorLayout.setHorizontalGroup(
            OpcionesAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcionesAdministradorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OpcionesAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelUsuarioAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(OpcionesAdministradorLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(OpcionesAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BotonCerrarSesiónAdministrador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonDarDeBajaUsuarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonVerReputaciónDeVoluntarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(BotonGenerarReporte, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );
        OpcionesAdministradorLayout.setVerticalGroup(
            OpcionesAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcionesAdministradorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelUsuarioAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200)
                .addComponent(BotonGenerarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(BotonDarDeBajaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(BotonVerReputaciónDeVoluntarios, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addComponent(BotonCerrarSesiónAdministrador)
                .addGap(50, 50, 50))
        );

        ContenedorPrincipalAdministrador.setBackground(new java.awt.Color(102, 102, 102));
        ContenedorPrincipalAdministrador.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout ContenedorPrincipalAdministradorLayout = new javax.swing.GroupLayout(ContenedorPrincipalAdministrador);
        ContenedorPrincipalAdministrador.setLayout(ContenedorPrincipalAdministradorLayout);
        ContenedorPrincipalAdministradorLayout.setHorizontalGroup(
            ContenedorPrincipalAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 922, Short.MAX_VALUE)
        );
        ContenedorPrincipalAdministradorLayout.setVerticalGroup(
            ContenedorPrincipalAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(OpcionesAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContenedorPrincipalAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OpcionesAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ContenedorPrincipalAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGenerarReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonGenerarReporteActionPerformed

    private void BotonVerReputaciónDeVoluntariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerReputaciónDeVoluntariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonVerReputaciónDeVoluntariosActionPerformed

    private void BotonDarDeBajaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDarDeBajaUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonDarDeBajaUsuariosActionPerformed

    private void BotonCerrarSesiónAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrarSesiónAdministradorActionPerformed
        // TODO add your handling code here:
        mainFrame.setInicioSesion();
    }//GEN-LAST:event_BotonCerrarSesiónAdministradorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCerrarSesiónAdministrador;
    private javax.swing.JButton BotonDarDeBajaUsuarios;
    private javax.swing.JButton BotonGenerarReporte;
    private javax.swing.JButton BotonVerReputaciónDeVoluntarios;
    private javax.swing.JPanel ContenedorPrincipalAdministrador;
    private javax.swing.JLabel LabelUsuarioAdministrador;
    private javax.swing.JPanel OpcionesAdministrador;
    // End of variables declaration//GEN-END:variables
}
