/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.gui;

/**
 *
 * @author Tincho
 */
public class VistaVeterinario extends javax.swing.JPanel {

    private Main mainFrame;
   
    public VistaVeterinario(Main mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
    }
    
    public VistaVeterinario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OpcionesVistaVeterinario = new javax.swing.JPanel();
        LabelUsuarioVeterinario = new javax.swing.JLabel();
        BotonActualizarEstadoDeSaludDeUnGato = new javax.swing.JButton();
        BotonEmitirdiagnosticoYTratamiento = new javax.swing.JButton();
        BotonVerHistorialMedicoDeUnGato = new javax.swing.JButton();
        BotonCerrarSesiónAdministrador = new javax.swing.JButton();
        ContenedorPrincipalVeterinario = new javax.swing.JPanel();

        setBackground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setMinimumSize(new java.awt.Dimension(1200, 800));

        OpcionesVistaVeterinario.setBackground(new java.awt.Color(51, 51, 51));

        LabelUsuarioVeterinario.setFont(new java.awt.Font("Aptos", 0, 24)); // NOI18N
        LabelUsuarioVeterinario.setForeground(new java.awt.Color(255, 255, 255));
        LabelUsuarioVeterinario.setText("Usuario:");
        LabelUsuarioVeterinario.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        BotonActualizarEstadoDeSaludDeUnGato.setBackground(new java.awt.Color(0, 102, 153));
        BotonActualizarEstadoDeSaludDeUnGato.setFont(new java.awt.Font("Aptos", 0, 18)); // NOI18N
        BotonActualizarEstadoDeSaludDeUnGato.setForeground(new java.awt.Color(255, 255, 255));
        BotonActualizarEstadoDeSaludDeUnGato.setText("<HTML>Actualizar estado de salud de un gato</HTML>");
        BotonActualizarEstadoDeSaludDeUnGato.setBorderPainted(false);
        BotonActualizarEstadoDeSaludDeUnGato.setMaximumSize(new java.awt.Dimension(200, 50));
        BotonActualizarEstadoDeSaludDeUnGato.setMinimumSize(new java.awt.Dimension(200, 50));
        BotonActualizarEstadoDeSaludDeUnGato.setPreferredSize(new java.awt.Dimension(200, 50));
        BotonActualizarEstadoDeSaludDeUnGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarEstadoDeSaludDeUnGatoActionPerformed(evt);
            }
        });

        BotonEmitirdiagnosticoYTratamiento.setBackground(new java.awt.Color(0, 102, 153));
        BotonEmitirdiagnosticoYTratamiento.setFont(new java.awt.Font("Aptos", 0, 18)); // NOI18N
        BotonEmitirdiagnosticoYTratamiento.setForeground(new java.awt.Color(255, 255, 255));
        BotonEmitirdiagnosticoYTratamiento.setText("<HTML>Emitir diagnóstico y tratamiento</HTML>");
        BotonEmitirdiagnosticoYTratamiento.setBorderPainted(false);
        BotonEmitirdiagnosticoYTratamiento.setMaximumSize(new java.awt.Dimension(200, 50));
        BotonEmitirdiagnosticoYTratamiento.setMinimumSize(new java.awt.Dimension(200, 50));
        BotonEmitirdiagnosticoYTratamiento.setPreferredSize(new java.awt.Dimension(200, 50));
        BotonEmitirdiagnosticoYTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEmitirdiagnosticoYTratamientoActionPerformed(evt);
            }
        });

        BotonVerHistorialMedicoDeUnGato.setBackground(new java.awt.Color(0, 102, 153));
        BotonVerHistorialMedicoDeUnGato.setFont(new java.awt.Font("Aptos", 0, 18)); // NOI18N
        BotonVerHistorialMedicoDeUnGato.setForeground(new java.awt.Color(255, 255, 255));
        BotonVerHistorialMedicoDeUnGato.setText("<HTML>Ver historial médico de un gato</HTML>");
        BotonVerHistorialMedicoDeUnGato.setBorderPainted(false);
        BotonVerHistorialMedicoDeUnGato.setMaximumSize(new java.awt.Dimension(200, 50));
        BotonVerHistorialMedicoDeUnGato.setMinimumSize(new java.awt.Dimension(200, 50));
        BotonVerHistorialMedicoDeUnGato.setPreferredSize(new java.awt.Dimension(200, 50));
        BotonVerHistorialMedicoDeUnGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVerHistorialMedicoDeUnGatoActionPerformed(evt);
            }
        });

        BotonCerrarSesiónAdministrador.setBackground(new java.awt.Color(0, 102, 153));
        BotonCerrarSesiónAdministrador.setFont(new java.awt.Font("Aptos", 0, 14)); // NOI18N
        BotonCerrarSesiónAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        BotonCerrarSesiónAdministrador.setText("Cerrar Sesión");
        BotonCerrarSesiónAdministrador.setBorderPainted(false);
        BotonCerrarSesiónAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrarSesiónAdministradorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OpcionesVistaVeterinarioLayout = new javax.swing.GroupLayout(OpcionesVistaVeterinario);
        OpcionesVistaVeterinario.setLayout(OpcionesVistaVeterinarioLayout);
        OpcionesVistaVeterinarioLayout.setHorizontalGroup(
            OpcionesVistaVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcionesVistaVeterinarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OpcionesVistaVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelUsuarioVeterinario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(OpcionesVistaVeterinarioLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(OpcionesVistaVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BotonCerrarSesiónAdministrador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonEmitirdiagnosticoYTratamiento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonVerHistorialMedicoDeUnGato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonActualizarEstadoDeSaludDeUnGato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)))
                .addContainerGap())
        );
        OpcionesVistaVeterinarioLayout.setVerticalGroup(
            OpcionesVistaVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcionesVistaVeterinarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelUsuarioVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215)
                .addComponent(BotonActualizarEstadoDeSaludDeUnGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(BotonEmitirdiagnosticoYTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(BotonVerHistorialMedicoDeUnGato, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(BotonCerrarSesiónAdministrador)
                .addGap(50, 50, 50))
        );

        ContenedorPrincipalVeterinario.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout ContenedorPrincipalVeterinarioLayout = new javax.swing.GroupLayout(ContenedorPrincipalVeterinario);
        ContenedorPrincipalVeterinario.setLayout(ContenedorPrincipalVeterinarioLayout);
        ContenedorPrincipalVeterinarioLayout.setHorizontalGroup(
            ContenedorPrincipalVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 922, Short.MAX_VALUE)
        );
        ContenedorPrincipalVeterinarioLayout.setVerticalGroup(
            ContenedorPrincipalVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(OpcionesVistaVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContenedorPrincipalVeterinario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OpcionesVistaVeterinario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ContenedorPrincipalVeterinario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonActualizarEstadoDeSaludDeUnGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarEstadoDeSaludDeUnGatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonActualizarEstadoDeSaludDeUnGatoActionPerformed

    private void BotonEmitirdiagnosticoYTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEmitirdiagnosticoYTratamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonEmitirdiagnosticoYTratamientoActionPerformed

    private void BotonVerHistorialMedicoDeUnGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerHistorialMedicoDeUnGatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonVerHistorialMedicoDeUnGatoActionPerformed

    private void BotonCerrarSesiónAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrarSesiónAdministradorActionPerformed
        // TODO add your handling code here:
        mainFrame.setInicioSesion();
    }//GEN-LAST:event_BotonCerrarSesiónAdministradorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizarEstadoDeSaludDeUnGato;
    private javax.swing.JButton BotonCerrarSesiónAdministrador;
    private javax.swing.JButton BotonEmitirdiagnosticoYTratamiento;
    private javax.swing.JButton BotonVerHistorialMedicoDeUnGato;
    private javax.swing.JPanel ContenedorPrincipalVeterinario;
    private javax.swing.JLabel LabelUsuarioVeterinario;
    private javax.swing.JPanel OpcionesVistaVeterinario;
    // End of variables declaration//GEN-END:variables
}
