/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.gui;

/**
 *
 * @author Tincho
 */
public class VistaVoluntario extends javax.swing.JPanel {

    private Main mainFrame;

    public VistaVoluntario(Main mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
    }
    
    public VistaVoluntario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OpcionesVoluntario = new javax.swing.JPanel();
        LabelUsuarioVoluntario = new javax.swing.JLabel();
        BotonCerrarSesionVoluntario = new javax.swing.JButton();
        BotonRegistrarPuntoDeAvistamiento = new javax.swing.JButton();
        BotonRegistarGato = new javax.swing.JButton();
        BotonAsignarGatoAFamilia = new javax.swing.JButton();
        BotonRegistrarVisitaDeSeguimiento = new javax.swing.JButton();
        BotonVerCalendarioDeTareas = new javax.swing.JButton();
        ContenedorPrincipalVoluntario = new javax.swing.JPanel();

        setBackground(new java.awt.Color(51, 51, 51));

        OpcionesVoluntario.setBackground(new java.awt.Color(51, 51, 51));
        OpcionesVoluntario.setPreferredSize(new java.awt.Dimension(272, 800));

        LabelUsuarioVoluntario.setFont(new java.awt.Font("Aptos", 0, 24)); // NOI18N
        LabelUsuarioVoluntario.setForeground(new java.awt.Color(255, 255, 255));
        LabelUsuarioVoluntario.setText("Usuario:");
        LabelUsuarioVoluntario.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        BotonCerrarSesionVoluntario.setBackground(new java.awt.Color(0, 102, 153));
        BotonCerrarSesionVoluntario.setFont(new java.awt.Font("Aptos", 0, 14)); // NOI18N
        BotonCerrarSesionVoluntario.setForeground(new java.awt.Color(255, 255, 255));
        BotonCerrarSesionVoluntario.setText("Cerrar sesión");
        BotonCerrarSesionVoluntario.setBorderPainted(false);
        BotonCerrarSesionVoluntario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrarSesionVoluntarioActionPerformed(evt);
            }
        });

        BotonRegistrarPuntoDeAvistamiento.setBackground(new java.awt.Color(0, 102, 153));
        BotonRegistrarPuntoDeAvistamiento.setFont(new java.awt.Font("Aptos", 0, 18)); // NOI18N
        BotonRegistrarPuntoDeAvistamiento.setForeground(new java.awt.Color(255, 255, 255));
        BotonRegistrarPuntoDeAvistamiento.setText("<HTML>Registrar punto de avistamiento</HTML>");
        BotonRegistrarPuntoDeAvistamiento.setBorderPainted(false);

        BotonRegistarGato.setBackground(new java.awt.Color(0, 102, 153));
        BotonRegistarGato.setFont(new java.awt.Font("Aptos", 0, 18)); // NOI18N
        BotonRegistarGato.setForeground(new java.awt.Color(255, 255, 255));
        BotonRegistarGato.setText("Registrar gato");
        BotonRegistarGato.setBorderPainted(false);

        BotonAsignarGatoAFamilia.setBackground(new java.awt.Color(0, 102, 153));
        BotonAsignarGatoAFamilia.setFont(new java.awt.Font("Aptos", 0, 18)); // NOI18N
        BotonAsignarGatoAFamilia.setForeground(new java.awt.Color(255, 255, 255));
        BotonAsignarGatoAFamilia.setText("Asignar gato a familia");
        BotonAsignarGatoAFamilia.setBorderPainted(false);

        BotonRegistrarVisitaDeSeguimiento.setBackground(new java.awt.Color(0, 102, 153));
        BotonRegistrarVisitaDeSeguimiento.setFont(new java.awt.Font("Aptos", 0, 18)); // NOI18N
        BotonRegistrarVisitaDeSeguimiento.setForeground(new java.awt.Color(255, 255, 255));
        BotonRegistrarVisitaDeSeguimiento.setText("<HTML>Registrar visita de seguimiento</HTML>");
        BotonRegistrarVisitaDeSeguimiento.setBorderPainted(false);

        BotonVerCalendarioDeTareas.setBackground(new java.awt.Color(0, 102, 153));
        BotonVerCalendarioDeTareas.setFont(new java.awt.Font("Aptos", 0, 18)); // NOI18N
        BotonVerCalendarioDeTareas.setForeground(new java.awt.Color(255, 255, 255));
        BotonVerCalendarioDeTareas.setText("<HTML>Ver calendario de tareas</HTML>");
        BotonVerCalendarioDeTareas.setBorderPainted(false);
        BotonVerCalendarioDeTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVerCalendarioDeTareasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OpcionesVoluntarioLayout = new javax.swing.GroupLayout(OpcionesVoluntario);
        OpcionesVoluntario.setLayout(OpcionesVoluntarioLayout);
        OpcionesVoluntarioLayout.setHorizontalGroup(
            OpcionesVoluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OpcionesVoluntarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OpcionesVoluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelUsuarioVoluntario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OpcionesVoluntarioLayout.createSequentialGroup()
                        .addGap(0, 30, Short.MAX_VALUE)
                        .addGroup(OpcionesVoluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotonCerrarSesionVoluntario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonAsignarGatoAFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonRegistarGato, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonVerCalendarioDeTareas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonRegistrarVisitaDeSeguimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonRegistrarPuntoDeAvistamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)))
                .addContainerGap())
        );
        OpcionesVoluntarioLayout.setVerticalGroup(
            OpcionesVoluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcionesVoluntarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelUsuarioVoluntario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(BotonVerCalendarioDeTareas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(BotonRegistrarVisitaDeSeguimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(BotonAsignarGatoAFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(BotonRegistarGato, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(BotonRegistrarPuntoDeAvistamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(BotonCerrarSesionVoluntario)
                .addGap(50, 50, 50))
        );

        ContenedorPrincipalVoluntario.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout ContenedorPrincipalVoluntarioLayout = new javax.swing.GroupLayout(ContenedorPrincipalVoluntario);
        ContenedorPrincipalVoluntario.setLayout(ContenedorPrincipalVoluntarioLayout);
        ContenedorPrincipalVoluntarioLayout.setHorizontalGroup(
            ContenedorPrincipalVoluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 922, Short.MAX_VALUE)
        );
        ContenedorPrincipalVoluntarioLayout.setVerticalGroup(
            ContenedorPrincipalVoluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(OpcionesVoluntario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContenedorPrincipalVoluntario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OpcionesVoluntario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ContenedorPrincipalVoluntario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonVerCalendarioDeTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerCalendarioDeTareasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonVerCalendarioDeTareasActionPerformed

    private void BotonCerrarSesionVoluntarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrarSesionVoluntarioActionPerformed
        // TODO add your handling code here:
        mainFrame.setInicioSesion();
    }//GEN-LAST:event_BotonCerrarSesionVoluntarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAsignarGatoAFamilia;
    private javax.swing.JButton BotonCerrarSesionVoluntario;
    private javax.swing.JButton BotonRegistarGato;
    private javax.swing.JButton BotonRegistrarPuntoDeAvistamiento;
    private javax.swing.JButton BotonRegistrarVisitaDeSeguimiento;
    private javax.swing.JButton BotonVerCalendarioDeTareas;
    private javax.swing.JPanel ContenedorPrincipalVoluntario;
    private javax.swing.JLabel LabelUsuarioVoluntario;
    private javax.swing.JPanel OpcionesVoluntario;
    // End of variables declaration//GEN-END:variables
}
